# Generated by Django 3.0.8 on 2020-08-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('submitted_at',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
