# Generated by Django 3.0.8 on 2020-08-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20200815_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='packages.Package'),
        ),
    ]
